name: buil-test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and build
        run: |
          npm install
      - name: Format check
        run: |
          npm run format-check
      - name: Code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: tiny-virtual-dom-codecov
          fail_ci_if_error: true
          verbose: true
      - name: Test
        run: |
          npm test
# TODO: using ncc when packaging